version: "3.9"
services:

  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgres/data
    restart: always
    networks:
      - spring

  msvc_cursos:
    container_name: msvc_cursos
    image: blascodes/cursos:latest
    ports:
      - "8002:8002"
   # env_file:
   #   - ./msvc-cursos/.env
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DB_DATABASE: msvc_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      USUARIOS_URL:	ec2-44-210-124-157.compute-1.amazonaws.com:8001
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always

volumes:
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring
